postgresql 9.0.2 from fedora

diff --git a/postgresql/postgresql.init b/postgresql/postgresql.init
--- a/postgresql/postgresql.init
+++ b/postgresql/postgresql.init
@@ -1,95 +1,35 @@
 #!/bin/sh
+#
 # postgresql	This is the init script for starting up the PostgreSQL
-#		server
+#		server.
 #
 # chkconfig: - 64 36
-# description: Starts and stops the PostgreSQL backend daemon that handles \
-#	       all database requests.
+# description: PostgreSQL database server.
 # processname: postmaster
-# pidfile: /var/run/postmaster-9.0.pid
+# pidfile: /var/run/postmaster.PORT.pid
 
-# Version 6.5.3-2 Lamar Owen
-# Added code to determine if PGDATA exists, whether it is current version
-#     or not, and initdb if no PGDATA (initdb will not overwrite a database).
+# This script is slightly unusual in that the name of the daemon (postmaster)
+# is not the same as the name of the subsystem (postgresql)
 
-# Version 7.0 Lamar Owen
-# Added logging code
-# Changed PGDATA.
-
-# Version 7.0.2 Trond Eivind Glomsrd <teg@redhat.com>
-# use functions, add conditional restart
-          
-# Version 7.0.3 Lamar Owen <lamar@postgresql.org>
-# Check for the existence of functions before blindly using them 
-# in particular -- check for success () and failure () before using.
-# More Cross-distribution support -- PGVERSION variable, and docdir checks.
-
-# Version 7.1 Release Candidate Lamar Owen <lamar@postgresql.org>
-# initdb parameters have changed.
-
-# Version 7.1.2 Trond Eivind Glomsrd <teg@redhat.com>
-# Specify shell for su
-# Handle stop better - kill unwanted output, make it wait until the database is ready
-# Handle locales slightly differently - always using "C" isn't a valid option 
-# Kill output from database initialization 
-# Mark messages for translation
-
-# Version 7.1.2-2.PGDG Lamar Owen <lamar.owen@wgcr.org>
-# sync up.
-# Karl's fixes for some quoting issues.
-
-# Version 7.2b2 Lamar Owen <lamar.owen@wgcr.org>
-# version change.
-
-# Version 7.2 final.  Lamar Owen <lamar.owen@wgcr.org>
-# reload from Peter E.
-# Eliminate the pidof postmaster test in stop -- we're using pg_ctl so we don't need pidof.
-# Tested the $? return for the stop script -- it does in fact propagate.
-# TODO: multiple postmasters.
-
-# Version 7.3 Lamar Owen <lamar.owen@ramifordistat.net>
-# Multiple postmasters, courtesy Karl DeBisschop
-
-# Version 7.4 Lamar Owen.
-
-# Version 7.4.3 Tom Lane <tgl@sss.pgh.pa.us>
-# Support condstop for uninstall
-# Minor other changes suggested by Fernando Nasser.
-
-# Version 7.4.5 Tom Lane <tgl@sss.pgh.pa.us>
-# Rewrite to start postmaster directly, rather than via pg_ctl; this avoids
-# fooling the postmaster's stale-lockfile check by having too many
-# postgres-owned processes laying about.
-
-# Version 8.1 Devrim Gunduz <devrim@PostgreSQL.org>
-# Increased sleep time from 1 sec to 2 sec.
-
-# Version 8.2 Devrim Gunduz <devrim@CommandPrompt.com>
-# Set initdb as a seperate option.
-
-# Version 8.3 Devrim Gunduz <devrim@CommandPrompt.com>
-
-# Version 8.4 Devrim Gunduz <devrim@CommandPrompt.com>
-# Remove "sameuser" from initdb, to match the new hba conf file.
-
-# Version 8.5 Devrim Gunduz <devrim@CommandPrompt.com>
-# Get rid of duplicate PGDATA assignment.
-# Ensure pgstartup.log gets the right ownership/permissions during initdb
-
-# PGVERSION is the full package version, e.g., 8.4.0
-# Note: the specfile ordinarily updates this during install
+# PGVERSION is the full package version, e.g., 9.0.2
+# Note: the specfile inserts the correct value during package build
 PGVERSION=xxxx
-# PGMAJORVERSION is major version, e.g., 8.4 (this should match PG_VERSION)
+# PGMAJORVERSION is major version, e.g., 9.0 (this should match PG_VERSION)
 PGMAJORVERSION=`echo "$PGVERSION" | sed 's/^\([0-9]*\.[0-9]*\).*$/\1/'`
+# PREVMAJORVERSION is the previous major version, e.g., 8.4, for upgrades
+# Note: the specfile inserts the correct value during package build
+PREVMAJORVERSION=xxxx
+# PREVPGENGINE is the directory containing the previous postmaster executable
+# Note: the specfile inserts the correct value during package build
+PREVPGENGINE=xxxx
+# PGDOCDIR is the directory containing the package's documentation
+# Note: the specfile inserts the correct value during package build
+PGDOCDIR=xxxx
 
 # Source function library.
-INITD=/etc/rc.d/init.d
-. $INITD/functions
+. /etc/rc.d/init.d/functions
 
-# Get function listing for cross-distribution logic.
-TYPESET=`typeset -f|grep "declare"`
-
-# Get config.
+# Get network config.
 . /etc/sysconfig/network
 
 # Find the name of the script
@@ -113,6 +53,8 @@ PGENGINE=/usr/bin
 PGPORT=5432
 PGDATA=/var/lib/pgsql/data
 PGLOG=/var/lib/pgsql/pgstartup.log
+# Value to set as postmaster process's oom_adj
+PG_OOM_ADJ=-17
 
 # Override defaults from /etc/sysconfig/pgsql if file is present
 [ -f /etc/sysconfig/pgsql/${NAME} ] && . /etc/sysconfig/pgsql/${NAME}
@@ -120,21 +62,20 @@ PGLOG=/var/lib/pgsql/pgstartup.log
 export PGDATA
 export PGPORT
 
-# Check that networking is up.
-# Pretty much need it for postmaster.
-[ "${NETWORKING}" = "no" ] && exit 0
-
-[ -f "$PGENGINE/postmaster" ] || exit 1
+lockfile="/var/lock/subsys/${NAME}"
+pidfile="/var/run/postmaster.${PGPORT}.pid"
 
 script_result=0
 
 start(){
+	[ -x "$PGENGINE/postmaster" ] || exit 5
+
 	PSQL_START=$"Starting ${NAME} service: "
 
 	# Make sure startup-time log file is valid
 	if [ ! -e "$PGLOG" -a ! -h "$PGLOG" ]
 	then
-		touch "$PGLOG" || exit 1
+		touch "$PGLOG" || exit 4
 		chown postgres:postgres "$PGLOG"
 		chmod go-rwx "$PGLOG"
 		[ -x /sbin/restorecon ] && /sbin/restorecon "$PGLOG"
@@ -143,53 +84,43 @@ start(){
 	# Check for the PGDATA structure
 	if [ -f "$PGDATA/PG_VERSION" ] && [ -d "$PGDATA/base" ]
 	then
-	# Check version of existing PGDATA
-
-		if [ x`cat "$PGDATA/PG_VERSION"` != x"$PGMAJORVERSION" ]
+		# Check version of existing PGDATA
+		if [ x`cat "$PGDATA/PG_VERSION"` = x"$PGMAJORVERSION" ]
 		then
-			SYSDOCDIR="(Your System's documentation directory)"
-			if [ -d "/usr/doc/postgresql-$PGVERSION" ]
-			then
-				SYSDOCDIR=/usr/doc
-			fi
-			if [ -d "/usr/share/doc/postgresql-$PGVERSION" ]
-			then
-				SYSDOCDIR=/usr/share/doc
-			fi
-			if [ -d "/usr/doc/packages/postgresql-$PGVERSION" ]
-			then
-				SYSDOCDIR=/usr/doc/packages
-			fi
-			if [ -d "/usr/share/doc/packages/postgresql-$PGVERSION" ]
-			then
-				SYSDOCDIR=/usr/share/doc/packages
-			fi
+			: A-OK
+		elif [ x`cat "$PGDATA/PG_VERSION"` = x"$PREVMAJORVERSION" ]
+		then
 			echo
 			echo $"An old version of the database format was found."
-			echo $"You need to upgrade the data format before using PostgreSQL."
-			echo $"See $SYSDOCDIR/postgresql-$PGVERSION/README.rpm-dist for more information."
+			echo $"Use \"service postgresql upgrade\" to upgrade to version $PGMAJORVERSION."
+			echo $"See $PGDOCDIR/README.rpm-dist for more information."
+			exit 1
+		else
+			echo
+			echo $"An old version of the database format was found."
+			echo $"You need to dump and reload before using PostgreSQL $PGMAJORVERSION."
+			echo $"See $PGDOCDIR/README.rpm-dist for more information."
 			exit 1
 		fi
-
-	# No existing PGDATA! Warn the user to initdb it.
-
 	else
+		# No existing PGDATA! Warn the user to initdb it.
 		echo
-		echo "$PGDATA is missing. Use \"service postgresql initdb\" to initialize the cluster first."
+                echo $"$PGDATA is missing. Use \"service postgresql initdb\" to initialize the cluster first."
 		echo_failure
 		echo
 		exit 1
  	fi
 
 	echo -n "$PSQL_START"
+	test x"$PG_OOM_ADJ" != x && echo "$PG_OOM_ADJ" > /proc/self/oom_adj
 	$SU -l postgres -c "$PGENGINE/postmaster -p '$PGPORT' -D '$PGDATA' ${PGOPTS} &" >> "$PGLOG" 2>&1 < /dev/null
 	sleep 2
-	pid=`pidof -s "$PGENGINE/postmaster"`
-	if [ $pid ] && [ -f "$PGDATA/postmaster.pid" ]
+	pid=`head -n 1 "$PGDATA/postmaster.pid" 2>/dev/null`
+	if [ "x$pid" != x ]
 	then
 		success "$PSQL_START"
-		touch /var/lock/subsys/${NAME}
-		head -n 1 "$PGDATA/postmaster.pid" > "/var/run/postmaster.${PGPORT}.pid"
+		touch "$lockfile"
+		echo $pid > "$pidfile"
 		echo
 	else
 		failure "$PSQL_START"
@@ -200,18 +131,24 @@ start(){
 
 stop(){
 	echo -n $"Stopping ${NAME} service: "
-	$SU -l postgres -c "$PGENGINE/pg_ctl stop -D '$PGDATA' -s -m fast" > /dev/null 2>&1 < /dev/null
-	ret=$? 
-	if [ $ret -eq 0 ]
+	if [ -e "$lockfile" ]
 	then
+	    $SU -l postgres -c "$PGENGINE/pg_ctl stop -D '$PGDATA' -s -m fast" > /dev/null 2>&1 < /dev/null
+	    ret=$? 
+	    if [ $ret -eq 0 ]
+	    then
 		echo_success
-	else
+		rm -f "$pidfile"
+		rm -f "$lockfile"
+	    else
 		echo_failure
 		script_result=1
+	    fi
+	else
+	    # not running; per LSB standards this is "ok"
+	    echo_success
 	fi
 	echo
-	rm -f "/var/run/postmaster.${PGPORT}.pid"
-	rm -f "/var/lock/subsys/${NAME}"
 }
 
 restart(){
@@ -219,58 +156,141 @@ restart(){
     start
 }
 
-initdb(){
-		if [ -f "$PGDATA/PG_VERSION" ]
-		then
-			echo "Data directory is not empty!"
-			echo_failure
-		else
-			echo -n $"Initializing database: "
-			if [ ! -e "$PGDATA" -a ! -h "$PGDATA" ]
-			then
-				mkdir -p "$PGDATA" || exit 1
-				chown postgres:postgres "$PGDATA"
-				chmod go-rwx "$PGDATA"
-			fi
-			# Clean up SELinux tagging for PGDATA
-			[ -x /sbin/restorecon ] && /sbin/restorecon "$PGDATA"
-
-			# Make sure the startup-time log file is OK, too
-			if [ ! -e "$PGLOG" -a ! -h "$PGLOG" ]
-			then
-				touch "$PGLOG" || exit 1
-				chown postgres:postgres "$PGLOG"
-				chmod go-rwx "$PGLOG"
-				[ -x /sbin/restorecon ] && /sbin/restorecon "$PGLOG"
-			fi
-
-			# Initialize the database
-			$SU -l postgres -c "$PGENGINE/initdb --pgdata='$PGDATA' --auth='ident'" >> "$PGLOG" 2>&1 < /dev/null
-
-			# Create directory for postmaster log
-			mkdir "$PGDATA/pg_log"
-			chown postgres:postgres "$PGDATA/pg_log"
-			chmod go-rwx "$PGDATA/pg_log"
-
-			[ -f "$PGDATA/PG_VERSION" ] && echo_success
-			[ ! -f "$PGDATA/PG_VERSION" ] && echo_failure
-			echo
-		fi
-}
 condrestart(){
-    [ -e /var/lock/subsys/${NAME} ] && restart
-}
-
-condstop(){
-    [ -e /var/lock/subsys/${NAME} ] && stop
+    [ -e "$lockfile" ] && restart || :
 }
 
 reload(){
     $SU -l postgres -c "$PGENGINE/pg_ctl reload -D '$PGDATA' -s" > /dev/null 2>&1 < /dev/null
 }
 
-# This script is slightly unusual in that the name of the daemon (postmaster)
-# is not the same as the name of the subsystem (postgresql)
+# code shared between initdb and upgrade actions
+perform_initdb(){
+	if [ ! -e "$PGDATA" -a ! -h "$PGDATA" ]
+	then
+		mkdir -p "$PGDATA" || return 1
+		chown postgres:postgres "$PGDATA"
+		chmod go-rwx "$PGDATA"
+	fi
+	# Clean up SELinux tagging for PGDATA
+	[ -x /sbin/restorecon ] && /sbin/restorecon "$PGDATA"
+
+	# Make sure the startup-time log file is OK, too
+	if [ ! -e "$PGLOG" -a ! -h "$PGLOG" ]
+	then
+		touch "$PGLOG" || return 1
+		chown postgres:postgres "$PGLOG"
+		chmod go-rwx "$PGLOG"
+		[ -x /sbin/restorecon ] && /sbin/restorecon "$PGLOG"
+	fi
+
+	# Initialize the database
+	$SU -l postgres -c "$PGENGINE/initdb --pgdata='$PGDATA' --auth='ident'" >> "$PGLOG" 2>&1 < /dev/null
+
+	# Create directory for postmaster log
+	mkdir "$PGDATA/pg_log"
+	chown postgres:postgres "$PGDATA/pg_log"
+	chmod go-rwx "$PGDATA/pg_log"
+
+	if [ -f "$PGDATA/PG_VERSION" ]
+	then
+	    return 0
+	fi
+	return 1
+}
+
+initdb(){
+    if [ -f "$PGDATA/PG_VERSION" ]
+    then
+	echo -n $"Data directory is not empty!"
+	echo_failure
+	echo
+	script_result=1
+    else
+	echo -n $"Initializing database: "
+	if perform_initdb
+	then
+	    echo_success
+	else
+	    echo_failure
+	    script_result=1
+	fi
+	echo
+    fi
+}
+
+upgrade(){
+    # must see previous version in PG_VERSION
+    if [ ! -f "$PGDATA/PG_VERSION" -o \
+	 x`cat "$PGDATA/PG_VERSION"` != x"$PREVMAJORVERSION" ]
+    then
+	echo
+	echo $"Cannot upgrade because database is not of version $PREVMAJORVERSION."
+	echo_failure
+	echo
+	exit 1
+    fi
+    if [ ! -x "$PGENGINE/pg_upgrade" ]
+    then
+	echo
+	echo $"Please install the postgresql-upgrade RPM."
+	echo_failure
+	echo
+	exit 5
+    fi
+    # Make sure service is stopped
+    stop
+
+    echo -n $"Upgrading database: "
+
+    # Set up log file for pg_upgrade
+    PGUPLOG=/var/lib/pgsql/pgupgrade.log
+    rm -f "$PGUPLOG"
+    touch "$PGUPLOG" || exit 1
+    chown postgres:postgres "$PGUPLOG"
+    chmod go-rwx "$PGUPLOG"
+    [ -x /sbin/restorecon ] && /sbin/restorecon "$PGUPLOG"
+
+    # Move old DB to PGDATAOLD
+    PGDATAOLD="${PGDATA}-old"
+    rm -rf "$PGDATAOLD"
+    mv "$PGDATA" "$PGDATAOLD" || exit 1
+
+    # Create empty new-format database
+    if perform_initdb
+    then
+	# Do the upgrade
+	$SU -l postgres -c "$PGENGINE/pg_upgrade \
+		'--old-bindir=$PREVPGENGINE' \
+		'--new-bindir=$PGENGINE' \
+		'--old-datadir=$PGDATAOLD' \
+		'--new-datadir=$PGDATA' \
+		--link \
+		'--old-port=$PGPORT' '--new-port=$PGPORT' \
+		--user=postgres" >> "$PGUPLOG" 2>&1 < /dev/null
+	if [ $? -ne 0 ]
+	then
+	    # pg_upgrade failed
+	    script_result=1
+	fi
+    else
+	# initdb failed
+	script_result=1
+    fi
+
+    if [ $script_result -eq 0 ]
+    then
+	    echo_success
+    else
+	    # Clean up after failure
+	    rm -rf "$PGDATA"
+	    mv "$PGDATAOLD" "$PGDATA"
+
+	    echo_failure
+    fi
+    echo
+    echo $"See $PGUPLOG for details."
+}
 
 # See how we were called.
 case "$1" in
@@ -281,27 +301,30 @@ case "$1" in
 	stop
 	;;
   status)
-	status -p /var/run/postmaster.${PGPORT}.pid
+	status -p "$pidfile" postmaster
 	script_result=$?
 	;;
   restart)
 	restart
 	;;
+  condrestart|try-restart)
+	condrestart
+	;;
+  reload)
+	reload
+	;;
+  force-reload)
+	restart
+	;;
   initdb)
 	initdb
 	;;
-  condrestart)
-	condrestart
-	;;
-  condstop)
-	condstop
-	;;
-  reload|force-reload)
-	reload
+  upgrade)
+	upgrade
 	;;
   *)
-	echo $"Usage: $0 {start|stop|status|restart|condrestart|condstop|reload|force-reload|initdb}"
-	exit 1
+	echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload|initdb|upgrade}"
+	exit 2
 esac
 
 exit $script_result
